/**
 * 설문 결과 목 응답 데이터 (요청응답모음.md 기반)
 * 실제 API 호출 없이 프론트 디자인 확인용으로 사용
 */
import type { PreviewResponse } from "./types"

export const MOCK_PREVIEW_RESPONSE: PreviewResponse = {
  survey: {
    id: 1,
    slug: "founder-fit-10-final",
    version: 1,
    survey_code: "A",
    scoring_version: "founder_fit_v1",
    title: "창업 성향 설문 10문항 최종",
    description:
      "비회원도 바로 응답하고 base36 추천 코드를 받을 수 있는 현재 활성 설문 정의다.",
    question_count: 10,
  },
  survey_response_id: 12,
  profile: {
    auth_user_uuid: null,
    profile_code: "r3a3lz4o0x8w1f2j",
    profile_schema_version: 3,
    survey_response_id: 12,
    survey_slug: "founder-fit-10-final",
    survey_version: 1,
    survey_code: "A",
    scoring_version: "founder_fit_v1",
    share_path: "/example/two-tower/r3a3lz4o0x8w1f2j",
    share_url: "http://localhost:3000/example/two-tower/r3a3lz4o0x8w1f2j",
    source: "survey",
    updated_at: "2026-06-21T11:22:33.456789+00:00",
    raw_answers: {
      q1: "A",
      q2: "C",
      q3: "D",
      q4: "A",
      q5: "C",
      q6: "A",
      q7: "B",
      q8: "A",
      q9: "D",
      q10: ["A", "D"],
    },
    user_profile: {
      user_id: "survey_a_preview",
      profile_name: "설문 결과 프로필",
      preferred_category_code: "CS100005",
      budget_level: 0.28,
      stability_level: 0.82,
      subway_dependency_level: 0.11,
      weekend_preference_level: 0.72,
      evening_preference_level: 0.36,
      resident_focus_level: 0.84,
      worker_focus_level: 0.15,
      rent_sensitivity_level: 0.74,
      competition_tolerance_level: 0.19,
    },
  },
  prediction: {
    trained_at: "2026-06-21T11:22:33.456789+00:00",
    model_signature: "onboarding_two_tower:2026-06-21T11:22:33.456789+00:00",
    top_k: 5,
    profile_code: "r3a3lz4o0x8w1f2j",
    profile_schema_version: 3,
    survey_code: "A",
    share_path: "/example/two-tower/r3a3lz4o0x8w1f2j",
    share_url: "http://localhost:3000/example/two-tower/r3a3lz4o0x8w1f2j",
    user_profile: {
      user_id: "survey_a_preview",
      profile_name: "설문 결과 프로필",
      preferred_category_code: "CS100005",
      budget_level: 0.28,
      stability_level: 0.82,
      subway_dependency_level: 0.11,
      weekend_preference_level: 0.72,
      evening_preference_level: 0.36,
      resident_focus_level: 0.84,
      worker_focus_level: 0.15,
      rent_sensitivity_level: 0.74,
      competition_tolerance_level: 0.19,
    },
    recommendations: [
      {
        rank: 1,
        score: 3.582114,
        item_id: "11230536:CS100005",
        area_name: "망원2동",
        service_category_name: "제과점",
        area_profile_type: "residential",
        sales_amount: 1950000000,
        weekend_sales_ratio: 0.52,
        evening_sales_ratio: 0.22,
        resident_population: 23110,
        worker_population: 9110,
        subway_commercial_trend_score: 0.73,
        category_opportunity_score: 0.68,
        demand_gap_score: 0.59,
      },
      {
        rank: 2,
        score: 3.214782,
        item_id: "11140587:CS100005",
        area_name: "연남동",
        service_category_name: "제과점",
        area_profile_type: "mixed",
        sales_amount: 2340000000,
        weekend_sales_ratio: 0.61,
        evening_sales_ratio: 0.29,
        resident_population: 18400,
        worker_population: 12300,
        subway_commercial_trend_score: 0.81,
        category_opportunity_score: 0.72,
        demand_gap_score: 0.45,
      },
      {
        rank: 3,
        score: 2.981345,
        item_id: "11350612:CS100005",
        area_name: "성수1가",
        service_category_name: "제과점",
        area_profile_type: "office",
        sales_amount: 3120000000,
        weekend_sales_ratio: 0.38,
        evening_sales_ratio: 0.41,
        resident_population: 8900,
        worker_population: 31200,
        subway_commercial_trend_score: 0.89,
        category_opportunity_score: 0.61,
        demand_gap_score: 0.52,
      },
      {
        rank: 4,
        score: 2.756891,
        item_id: "11200498:CS100005",
        area_name: "합정동",
        service_category_name: "제과점",
        area_profile_type: "mixed",
        sales_amount: 2780000000,
        weekend_sales_ratio: 0.49,
        evening_sales_ratio: 0.35,
        resident_population: 15600,
        worker_population: 14800,
        subway_commercial_trend_score: 0.77,
        category_opportunity_score: 0.58,
        demand_gap_score: 0.41,
      },
      {
        rank: 5,
        score: 2.543217,
        item_id: "11410322:CS100005",
        area_name: "이태원1동",
        service_category_name: "제과점",
        area_profile_type: "commercial",
        sales_amount: 1680000000,
        weekend_sales_ratio: 0.57,
        evening_sales_ratio: 0.48,
        resident_population: 6200,
        worker_population: 8400,
        subway_commercial_trend_score: 0.65,
        category_opportunity_score: 0.79,
        demand_gap_score: 0.71,
      },
    ],
  },
}

/** 상권 프로필 유형 한국어 라벨 */
export const AREA_PROFILE_LABELS: Record<string, string> = {
  residential: "주거형",
  office: "오피스형",
  commercial: "상업형",
  mixed: "혼합형",
}

/** 사용자 프로필 수치 한국어 라벨 */
export const PROFILE_METRIC_LABELS: Record<string, string> = {
  budget_level: "예산 수준",
  stability_level: "안정 추구",
  subway_dependency_level: "지하철 의존",
  weekend_preference_level: "주말 선호",
  evening_preference_level: "저녁 선호",
  resident_focus_level: "주민 집중",
  worker_focus_level: "직장인 집중",
  rent_sensitivity_level: "임대료 민감",
  competition_tolerance_level: "경쟁 수용",
}
